# Generated by Django 5.1.15 on 2026-08-17 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('request_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('restaurant_id', models.CharField(max_length=100)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('requested_by', models.CharField(default='Merchant', max_length=100)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('change_type', models.CharField(default='Menu / Info Update', max_length=100)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['restaurant_name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=100)),
                ('operating_hours', models.CharField(default='09:00 AM - 08:00 PM', max_length=100)),
                ('price_tier', models.CharField(default='$', max_length=10)),
                ('lat', models.FloatField(default=15.032)),
                ('lng', models.FloatField(default=120.686)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('image', models.URLField(blank=True, default='', max_length=1000)),
                ('images', models.JSONField(blank=True, default=list)),
                ('username', models.CharField(default='owner', max_length=100, unique=True)),
                ('password', models.CharField(default='password123', max_length=100)),
                ('occupancy', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('ingredients', models.TextField(blank=True, default='')),
                ('allergens', models.CharField(blank=True, default='', max_length=200)),
                ('health_indicators', models.CharField(blank=True, default='', max_length=200)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, default='', max_length=1000)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='api.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('operating_hours', models.CharField(default='09:00 AM - 08:00 PM', max_length=100)),
                ('lat', models.FloatField(default=15.032)),
                ('lng', models.FloatField(default=120.686)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.restaurant')),
            ],
            options={
                'ordering': ['branch_name'],
            },
        ),
        migrations.CreateModel(
            name='TouristAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='TouristItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account_key', models.CharField(db_index=True, help_text='Tourist username or email identifier', max_length=150)),
                ('itinerary_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('stops', models.JSONField(default=list)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tourist Itineraries',
                'ordering': ['user_account_key', 'name'],
                'unique_together': {('user_account_key', 'itinerary_id')},
            },
        ),
    ]
